version: '3.9'

services:

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: always
    depends_on:
      - redis